version: '3'

services:
  go-app:
    build: .
    ports:
      - "8080:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"
    command: start-dev
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: myself
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: jwtDb
    volumes:
      - pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"
